name: NodeJS SDK Wrapper CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  LT_USERNAME: ${{ secrets.LT_USERNAME }}
  LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
  PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
  LT_SDK_DEBUG: true
  SMARTUI_DEBUG: true

jobs:
  smartui-nodejs-sdk:
    name: Execute NodeJS SDK Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Execute NodeJS Wrapper
        run: |
          npm install
          npx smartui --version
          npx smartui exec node test.js --config smartui-web.json
